service: hanami-sandbox

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, "us-west-1"}
  vpc:
    securityGroupIds:
      - "sg-24abc65d"
    subnetIds:
      - "subnet-713e832a"

functions:
  hanami:
    handler: lambda.handler
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any

  db_prepare:
    handler: db_prepare.handler
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
