service: hanami-sandbox

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, "us-west-1"}

functions:
  hanami:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: any
