service: hanami-sandbox

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, "us-west-1"}

functions:
  hanami:
    handler: lambda.handler
    environment:
      DATABASE_URL: "sqlite://db/bookshelf_development.sqlite"
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any
